// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Drivee_Model_WebApi2
{
    public partial class Drivee_Model
    {
        /// <summary>
        /// model input class for Drivee_Model.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"order_timestamp")]
            public string Order_timestamp { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"distance_in_meters")]
            public float Distance_in_meters { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"duration_in_seconds")]
            public float Duration_in_seconds { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"tender_timestamp")]
            public string Tender_timestamp { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"driver_reg_date")]
            public string Driver_reg_date { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"driver_rating")]
            public float Driver_rating { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"carmodel")]
            public string Carmodel { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"carname")]
            public string Carname { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"platform")]
            public string Platform { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"pickup_in_meters")]
            public float Pickup_in_meters { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"pickup_in_seconds")]
            public float Pickup_in_seconds { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"price_start_local")]
            public float Price_start_local { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"price_bid_local")]
            public float Price_bid_local { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"is_done")]
            public string Is_done { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Drivee_Model.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"order_timestamp")]
            public float[] Order_timestamp { get; set; }

            [ColumnName(@"distance_in_meters")]
            public float Distance_in_meters { get; set; }

            [ColumnName(@"duration_in_seconds")]
            public float Duration_in_seconds { get; set; }

            [ColumnName(@"tender_timestamp")]
            public float[] Tender_timestamp { get; set; }

            [ColumnName(@"driver_reg_date")]
            public float[] Driver_reg_date { get; set; }

            [ColumnName(@"driver_rating")]
            public float Driver_rating { get; set; }

            [ColumnName(@"carmodel")]
            public float[] Carmodel { get; set; }

            [ColumnName(@"carname")]
            public float[] Carname { get; set; }

            [ColumnName(@"platform")]
            public float[] Platform { get; set; }

            [ColumnName(@"pickup_in_meters")]
            public float Pickup_in_meters { get; set; }

            [ColumnName(@"pickup_in_seconds")]
            public float Pickup_in_seconds { get; set; }

            [ColumnName(@"price_start_local")]
            public float Price_start_local { get; set; }

            [ColumnName(@"price_bid_local")]
            public float Price_bid_local { get; set; }

            [ColumnName(@"is_done")]
            public uint Is_done { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Drivee_Model.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("is_done");
            if (labelColumn == null)
            {
                throw new Exception("is_done column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
