// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

public partial class DriveeModel
{
    /// <summary>
    /// model input class for Drivee_Model.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"price_start_local")]
        public float Price_start_local { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for Drivee_Model.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"price_start_local")]
        public float[] Price_start_local { get; set; }

        [ColumnName(@"price_start_local_LB")]
        public float[] Price_start_local_LB { get; set; }

        [ColumnName(@"price_start_local_UB")]
        public float[] Price_start_local_UB { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath(@"Drivee_Model.mlnet");

    private static TimeSeriesPredictionEngine<ModelInput, ModelOutput>? _predictEngine;

    public static ModelOutput Predict(ModelInput input, int horizon = 1)
    {
        if (_predictEngine == null)
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            _predictEngine = mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }

        return _predictEngine.Predict(input, horizon);
    }

    private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
        return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
    }
}
//
