// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;

namespace Drivee_Model_WebApi2
{
    public partial class Drivee_Model
    {
        public const string RetrainFilePath =  @"C:\Users\dreamgonewithout\Downloads\Telegram Desktop\train.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"platform", @"platform", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"distance_in_meters", @"distance_in_meters"),new InputOutputColumnPair(@"duration_in_seconds", @"duration_in_seconds"),new InputOutputColumnPair(@"driver_rating", @"driver_rating"),new InputOutputColumnPair(@"pickup_in_meters", @"pickup_in_meters"),new InputOutputColumnPair(@"pickup_in_seconds", @"pickup_in_seconds"),new InputOutputColumnPair(@"price_start_local", @"price_start_local"),new InputOutputColumnPair(@"price_bid_local", @"price_bid_local")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"order_timestamp",outputColumnName:@"order_timestamp"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"tender_timestamp",outputColumnName:@"tender_timestamp"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"driver_reg_date",outputColumnName:@"driver_reg_date"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"carmodel",outputColumnName:@"carmodel"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"carname",outputColumnName:@"carname"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"platform",@"distance_in_meters",@"duration_in_seconds",@"driver_rating",@"pickup_in_meters",@"pickup_in_seconds",@"price_start_local",@"price_bid_local",@"order_timestamp",@"tender_timestamp",@"driver_reg_date",@"carmodel",@"carname"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"is_done",inputColumnName:@"is_done",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(new SdcaMaximumEntropyMulticlassTrainer.Options(){L1Regularization=0.25076777F,L2Regularization=0.03125F,LabelColumnName=@"is_done",FeatureColumnName=@"Features"}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
