// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Drivee_Model_WebApi2
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(2)]
            [ColumnName(@"distance_in_meters")]
            public float Distance_in_meters { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"duration_in_seconds")]
            public float Duration_in_seconds { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"driver_rating")]
            public float Driver_rating { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"pickup_in_meters")]
            public float Pickup_in_meters { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"pickup_in_seconds")]
            public float Pickup_in_seconds { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"price_start_local")]
            public float Price_start_local { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"price_bid_local")]
            public float Price_bid_local { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"is_done")]
            public string Is_done { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"distance_in_meters")]
            public float Distance_in_meters { get; set; }

            [ColumnName(@"duration_in_seconds")]
            public float Duration_in_seconds { get; set; }

            [ColumnName(@"driver_rating")]
            public float Driver_rating { get; set; }

            [ColumnName(@"pickup_in_meters")]
            public float Pickup_in_meters { get; set; }

            [ColumnName(@"pickup_in_seconds")]
            public float Pickup_in_seconds { get; set; }

            [ColumnName(@"price_start_local")]
            public float Price_start_local { get; set; }

            [ColumnName(@"price_bid_local")]
            public float Price_bid_local { get; set; }

            [ColumnName(@"is_done")]
            public float[] Is_done { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
